apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-ml-app
  labels:
    app: streamlit-ml
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit-ml
  template:
    metadata:
      labels:
        app: streamlit-ml
    spec:
      containers:
        - name: streamlit-container
          image: us-central1-docker.pkg.dev/mymltest-456111/ml-repo/streamlit-ml-app:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          env:
            - name: PORT
              value: "8080"
